### ISSUE TITLE
request  for  course “Generative Models” video

### ISSUE THREAD

**Issue by LeeeLiu** [jthickstun/gm-hw1#1]
- Excuse me，is  there  a  URL  where I can watch   “Generative Models”  course video?
- I could'nt  find  video  [here](https://courses.cs.washington.edu/courses/cse599i/20au/)

**Comment by jthickstun** [comment]
Hi LeeeLiu,

Sorry but I won't be able to release videos for this course. For video lectures on these topics I recommend Pieter's course:

https://sites.google.com/view/berkeley-cs294-158-sp20/home

Best,John
